TheScienceMuseum/collectionsonline

- .corc.template
- bin/server.js
- config.js
- package.json
- routes/index.js
- routes/plugins/error.js
- routes/search.js
- server.js
- templates/pages/error.html
- test/content-negotiation-test.js
- test/error-plugin.js
- test/error.plugin.js
- test/helpers/mock-elastic.js
- test/helpers/test-with-server.js
- test/routes-test.js
- test/search-filters.js
- test/static-file-test.js
refs #32 
* Adds elasticsearch dependency to the app, creates a new client based on .corc config and passes it to `server.js`
* `testWithServer` now creates and passes a noop mock elasticsearch client to the server which you can use to stub/spy/mock on
* Adds sinon dependency for stubbing/spying/mocking
* Adds error handler plugin for Hapi that responds correctly given the request `Accept` header (sends a nice page for text/html and sends an appropriately formatted JSON response for 'application/vnd.api+json')
* Adds tests for the plugin
For this to work you'll need to add elasticsearch config to your `.corc` file e.g.:
```js
{
"port": 8000,
"elasticsearch": {
"apiVersion": "1.7",
"host": "http://USERNAME:PASSWORD@DOMAIN/public",
"log": "trace"
}
}
```
> Adds elasticsearch dependency and error handler plugin

- .corc.template
- lib/transforms/search-results-to-jsonapi.js
- package.json
- routes/index.js
- routes/search.js
- test/transforms/search-results-to-jsonapi.js
This is a work in progress for #44 but safe to merge as it adds new functionality to just the search JSON endpoint
* Adds module to transform elasticsearch result
* Adds tests for transform
* Wires up transformed doc to endpoint
TODO (in another PR):
* Transform `@linked` docs into `relationships` and `included` for docs not on the object route
* Add test for transforming `relationships` and `included` docs
> Add transform for search results to jsonapi responses

- lib/transforms/search-results-to-jsonapi.js
- lib/type-mapping.js
- test/transforms/search-results-to-jsonapi.js
- test/type-mapping.js
The `TypeMapping` util allows us to convert type names and IDs between internal and external representations.
Examples:
```js
TypeMapping.toExternal('agent') // -> people
TypeMapping.toExternal('smg-archive-12345') // -> smg-documents-12345
TypeMapping.toInternal('people') // -> agent
TypeMapping.toInternal('smg-documents-12345') // -> smg-archive-12345
```
Currently the following mappings are supported (and vice versa):
* People => Agent
* Objects => Object
* Documents => Archive
This work was necessary in order to add the test (also included in PR) to ensure relationships from the index were extracted correctly and placed in the appropriate jsonapi `relationships` and `included` properties of the response document.
refs #44
> Add type mapping and test transform relationships

- routes/public.js
`hapi-negotiator` was stepping in because safari sends a `Accept: image/svg+xml` header. We actually don't want the plugin for this route so this PR explicitly disables it.
Explicitly disabling the plugin might be the intended behaviour, but I suspect not:
https://github.com/felipeleusin/hapi-negotiator/pull/10
fixes #83
> Disable hapi-negotiator plugin on plublic assets route

- client/routes/search.js
Query params object created in #134 was not passed in to client side ajax request, so it was no longer working
> uses queryparams object in client side ajax request #128

- routes/archive.js
- routes/object.js
- routes/person.js
- templates/layouts/default.html
- test/fixtures/copy-es-docs.js
- test/routes.test.js
If no media type is given we're currently just sending back an empty reply.
The twitter bot that scrapes our site to get the data for the twitter cards has no media type, but expects html as a response, so this sends an html response if no media type is specified.
> makes text/html default response if no media type given

- client/lib/slick-carousel.js
- templates/partials/records/record-imgpanel__controlbar.html
ref #270 
Button was using foundation's data toggles. Foundation's jquery function wasn't getting called on re-render. This fixes the button and removes dependency on foundation, for when we decide to get rid of jquery altogether
> makes cite button work 

- templates/partials/records/record-imgpanel__controlbar.html
PR #276 fixed the button on ajax load, but broke it on the initial render, this makes it work for both.
Note: Travis is failing because this branch is still using the old index
> fixes cite button not working on initial render #270

- templates/partials/search/results-list.html
see #279
This PR add the [figcaption](https://github.com/TheScienceMuseum/collectionsonline/blob/0c946971fcb7ee3b3b77de4e46afb5dd2b6db991/lib/transforms/search-results-to-template-data.js#L75-L90) value to the list view display.
> add description to list-view

- client/routes/search.js
- routes/analytics.js
- routes/index.js
- test/analytics.test.js
* Adds `POST /analytics` for registering analytics events
* Payload looks like `{ event: 'EVENT_NAME', data: 'misc data' }`
* Currently only one event available `RESULT_CLICK` where `data` is assumed to be the ID of an object in the collection
> Add analytics endpoint for registering result clicks

- client/lib/search-listener.js
- lib/transforms/search-results-to-template-data.js
- templates/partials/global/searchbox.html
- test/client/filter-searchbox.clienttest.js
see #343 
As the location for the museum is not yet in the index the filters under the searchbox is only working for categories
> Category blue pill

- client/lib/carousel.js
- client/styles/components/_carousel.scss
- templates/partials/records/carousel.html
Lazy loads images and transitions them from transparent to opaque, to avoid images later in the carousel from appearing before the first image, and briefly causing flashing/overlapping images
> lazy load images

- lib/facets/aggs-all.js
ref #403
For the aggregations on the 'all' tab, we were just using the 'name' field, which on objects is the category, but on people/organisations is their name. We're now only using the name field if the item is actually an object.
> fixes bug where orgs were showing as object type in filters

- schemas/search.js
see #399
[This code](https://github.com/TheScienceMuseum/collectionsonline/blob/f2fb6e8a3c05033e509d95424631da03894c306d/lib/search.js#L157-L159) will catch the empty query and return all the results.
> allow empty search which return all the results

- client/lib/archive-listeners.js
- client/routes/document.js
resolves #427.
Error was appearing because it was trying to attach an event listener to a non existent element. This PR removes one of the listeners that we're not using any more, and checks if the element exists before trying to add the other.
> deletes no longer used archive listener function

- client/lib/openseadragon.js
- package.json
ref #372 
Replaces openseadragon with a fork that solves the deepzoom issue.
> replaces osd to make zoom work

- lib/facets/aggs-all.js
- lib/facets/create-filters.js
- test/client/multiple-filters.clienttest.js
ref #420 
Allows multiple filters of the same facet to be selected when objects have more than one, by using an array for the filter instead of a single value.
I've also factored out the filter creation function from `aggs-all`, as it was almost identical to the filter creation function in `create-filters`
> Multiple filters

- client/templates.js
- lib/transforms/json-to-html-data.js
- templates/helpers/comma.js
- templates/partials/records/record-details.html
ref #409 
Moves comma logic to handlebars rather than server to avoid it showing in the url
> separates comma from value in details 

- lib/facets/aggs-all.js
- lib/facets/create-filters.js
- test/search-filters.test.js
#403 was reintroduced in the refactoring of the filters.
This pr fixes it and adds a regression test to make sure it doesn't happen again
> fixes org-name as type bug again

- routes/archive.js
- schemas/archive.js
because of #513, archives were not loading from the search page. They were using a schema with the format of the old ids. This schema was for a query that we're no longer using, so I've just deleted it.
> removes old archive schema

- client/routes/search.js
- client/templates.js
- templates/pages/search.html
If already in the search page, only the results are now re-rendered, rather than the whole page.
Solves issue #494
> only re-renders search results on search page

- lib/transforms/json-to-html-data.js
- lib/transforms/search-results-to-jsonapi.js
- lib/transforms/search-results-to-template-data.js
- test/images.test.js
Small updates to bring the code into line with the new index fields for the images and make the one image we currently have display correctly.
We've uncommented one test now, which brings the coverage up. Still won't quite be up to 100 until we have a few more images with the different values we can test (#491)
(diff coverage is only at 80% because I updated the code for the document images too, which still don't exist)
> updates get image functions for new index structure

- lib/search.js
- test/check-purchased.test.js
Prioritises location, then image for results: #578
Uses best fields rather than cross fields, provides better results for terms with apostrophes: #583
> relevance tweaks

- client/styles/components/_carousel.scss
- lib/transforms/json-to-html-data.js
- lib/transforms/search-results-to-jsonapi.js
- lib/transforms/search-results-to-template-data.js
- routes/object.js
- templates/pages/object.html
- templates/partials/records/single-image.html
Fix so that if an object only has one image it displays correctly. Also removes example images and uses correct image sizes. ref: #602
> single image display

- fixtures/users.js
- test/autocomplete.test.js
- test/client/routes/person.clienttest.js
Small tweak to the users fixture to remove the 'user' relationships (as it was too vague in the interface).
> Removed 'user' relationship type from user relationship list

- client/styles/components/_carousel.scss
- templates/partials/records/record-imgpanel__controlbar.html
ref #641, caption wasn't displaying for single images because 'hidden' class was applied, which was only being removed by the carousel (which doesn't exist for single images)
> shows caption for single images

- .travis.yml
We're having trouble deploying to the staging area from travis since adding this, so removing it for now and deploying to production manually until we can work it out
> deletes production-release script from travis yaml

- templates/layouts/default.html
see #717 
The links for the different format of images are created [here](https://github.com/TheScienceMuseum/collectionsonline/blob/7fa6ae6176a76c31a4157fb0f1c7d48d8666d2ed/lib/transforms/json-to-html-data.js#L441)
> use medium image format for opengraph

- lib/jsonapi-response.js
The database has the now the right values for the occupations (#518) so this PR delete a fix code we used to extract the right values from the Elasticsearch index
see #773
> retreive all occupations

- lib/helpers/search-results-to-template-data/title-page.js
- lib/transforms/search-results-to-template-data.js
- test/title-serp.test.js
if only on of the filter for categories, museum or gallery is selected and the search is empty (no query parameters defined for q, or empty string) we are add the name of the filter in the title of the page
see #699
> add title for serp

- lib/jsonapi-response.js
see  #778
delete location_is_relative property which is not useful in the api response
> delete location_is_relative from api result

- lib/query-params/query-params.js
- lib/search.js
- schemas/search.js
- test/random.test.js
ref #780
Allows addition of `random=n` as a query string, where `n` is a number between 1 and 50, and returns `n` random results
> Get random search results 

- client/lib/archive-listeners.js
- client/lib/get-qs.js
- client/lib/search-listener.js
- test/client/routes/document.clienttest.js
ref #867
When adding filters using the sidebar, they are now added to the url in lower case.
Queries were already case insensitive on the back end, so they now work both ways.
> lowercases filters in the url

- fixtures/museums.js
Site link should be to `http` not `https`
> fix https -> http link to science museum site

- client/lib/listeners/carousel.js
Only apply safari ios fix when on ios device
Ref #807 
For some reason, safari desktop could crash when making an image full screen. The change should no longer effect desktop and will only apply to mobile
> Ios image bugs

- test/client/images.clienttest.js
- test/client/routes/person.clienttest.js
Fixes the following test failure, caused by a index / record change.
```
✔ Element <.resultcard__figure> was visible after 389 milliseconds.
✖ Testing if attribute src of <.resultcard__figure img> equals "[secure]W/P/A/large_thumbnail_1862_0005__0001_.jpg".  - expected "[secure]W/P/A/large_thumbnail_1862_0005__0001_.jpg" but got: "[secure]W/P/A/large_thumbnail_1862_0005__0004_.jpg"
at Object.module.exports.Filtering on search page (/home/[secure]/build/TheScienceMuseum/collectionsonline/test/client/images.clienttest.js:7:15)
```
> fix test images.clienttest.js

- lib/helpers/jsonapi-response/sort-images.js
- lib/jsonapi-response.js
- lib/transforms/search-results-to-jsonapi.js
- package.json
- test/client/images.clienttest.js
- test/sort-images.test.js
Resolves the ordering of images (by position, priority and date [sort]) on object and document pages. Also ensure the correctly sorted (first image) is used in the search results pages.
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/983
_It seems image order has been broken of a while now and we just never noticed till we started using page ordering on the archive images._
I used [Lodash](https://lodash.com/docs/) `orderBy` to do the sorting, not sure if we want to avoid using it, but seemed nice and concise solution over writing a custom sort to handle multiple fields/types and asc/desc. But happy to revert back to standard JS if we feel that's cleaner.
Also not 100% sure if sorting the images in 'lib/transforms/search-results-to-jsonapi.js` prior to assigning a …
> Fix image order

- lib/facets/aggs-all.js
- lib/facets/create-filters.js
- test/routes.test.js
Categories are not working because the keyword field has been removed from the index.
This removes the keyword call, so will fix them
> fixes categories for elasticseasrch

- client/lib/listeners/carousel.js
- client/lib/listeners/osd-listener.js
- client/lib/openseadragon.js
- package.json
Openseadragon fixed the issue that caused us to need to fork it (https://github.com/openseadragon/openseadragon/issues/1017) so we can now go back to using the master branch.
This PR also stops safari crashing when we close fullscreen. Previously we were destroying the osd viewer every time the full screen was closed, then creating a new viewer every time another image was opened. We're now using the same viewer, just changing the tilesource.
> updates OpenSeadragon, stops safari crashing when closing full screen

- lib/search.js
ref #980, searching for exact name of an object should place it higher than less accurate results that are on display.
> gives higher boost to name matches

- client/lib/openseadragon.js
openseadragon now needs to be explicitly set to a variable when required
> requires osd correctly

- client/styles/base/_colour.scss
Brighten up document icon so it's clear when used on related documents (wide a dark background) etc.
> lighten purple used on document icons

- schemas/filter.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1204
By adding .allow('', null) to filters.js (not sure if that is the best / most sensible solution?)
// People
'filter[birth[date]]': Joi.number().allow('', null).integer().min(0),
'filter[death[date]]': Joi.number().allow('', null).integer().min(0)
> Allow dates to be null string

- client/templates.js
- lib/get-related-items.js
- lib/sort-related-items.js
- templates/helpers/ifcreator.js
- templates/partials/records/record-related-objects.html
- test/routes.test.js
ref #662
Gets related items that aren't just those created by the person (items they owned, portraits of them etc.), along with the relationship/role data (as per #1260).
> Get non-creator related objects for people

- lib/jsonapi-response.js
- templates/partials/records/record-top.html
Also removes usage of getLinks() in lib/jsonapi-response.js and instead uses a simplified links array in getChildren
> add a back link to MPH child pages

- client/styles/components/_result.scss
- routes/stats.js
Hopefully resolves 
https://github.com/TheScienceMuseum/collectionsonline/issues/1620
> fix result card css, image not full width of Edge

- client/styles/components/_record.scss
Added in a fixed height and overflow property to web descriptions, as the descriptions added to this ticket a while ago caused the heights of the records to differ wildly. This is a stopgap to fix this until a decision is made on how to style the web descriptions. I think having the descriptions appear in a modal, similar to how the images appear could be a good idea, but needs some thought on how to make accessible, whether the extra clicking on each record to see the entire description is a good user experience, etc.
> feat: overflow added to web descriptions

- client/lib/listeners/osd.js
Added conditional check for openseadragon configuration, to fix edge case where a carousel image may not have zooms, which are passed to handlebars and used to render ui, resulting in a server error
> fix: fixed openseadragon edge case

- lib/transforms/search-results-to-template-data.js
[Issue #1709](https://github.com/TheScienceMuseum/collectionsonline/issues/1709) - This change is to handle an edge case where values such as undefined and false are pulled into filterbadges. This happens because the createSelectedFilters creates and returns an object using values from the query params as a key. There are a few instances where those values can be falsy values, such as if the user entered wrong values into the url.
> feat: filtering out falsy values from filterbadges

- client/styles/components/_record.scss
- client/templates.js
- templates/helpers/ifWebAndPrimary.js
- templates/helpers/sphDescription.js
- templates/partials/records/record-sph-item.html
This formats as per other expandable descriptions.
Note I found a few records [without an initial description](https://collection.sciencemuseumgroup.org.uk/objects/co416960/album-of-cyanotypes-of-british-and-foreign-ferns-album-cyanotype), in these cases, I nick the first para from the longer part, similarly to `lib/helpers/json-to-html-data/format-description.js`.
Feels like there could be some refactoring of the different description types now, but i'm not sure how they're used elsewhere, or coming from disparate sources.
> add details to sph records with long descriptions

- client/styles/components/_home.scss
- templates/pages/home.html
Hey @evancp87 I just noticed this too.
I've just given the images their own clipping context outside of the foreground content.
> Awesomplete results cut off on mobile

- client/lib/listeners/carousel.js
- client/templates.js
- templates/helpers/formatCopyright.js
- templates/partials/records/record-sph-item.html
if multiple images (therefore possible multiple copyrights) the image carousel updates the displayed text.
Note sometimes that text is '... Mus**ue**m' [sic]! e.g. /objects/co8412068/hoover-%20constellation-vacuum-cleaner-with-attachments-vacuum-cleaner
> add sph image copyright

- client/lib/listeners/carousel.js
- client/lib/listeners/lightbox.js
- client/styles/components/_carousel.scss
- client/styles/components/_mediaplayer.scss
- client/templates.js
- lib/transforms/json-to-html-data.js
- templates/helpers/formatCopyright.js
- templates/pages/object.html
- templates/partials/records/record-sph-item.html
Seems there are some duplicate images across parts, at least on `/objects/co26704/rocket-locomotive-steam-locomotive`
which is the only multiple-images example I can find. Not the end of the world.
> add carousel for multiple sph images

- lib/transforms/search-results-to-jsonapi.js
@tobystokes The full path to the images should now be built correctly, at the api level, in line with how it is done on record pages
> feat: configured full path to image server

- routes/robot.js
Stop limiting indexing of categories
(not sure why we did this originally)
> remove /categories from robots.txt

- client/templates.js
Fix typo in Handlebars.registerPartial (record-sph-properties should be record-sph-priority-item)
Handlebars.registerPartial(
'records/record-sph-properties',
Fs.readFileSync('./templates/partials/records/record-sph-priority-item.html', 'utf8')
> fix error in registering handlbars template

- client/styles/components/_description-box.scss
Fixed [this issue](https://github.com/TheScienceMuseum/collectionsonline/issues/1792), where new styles applied to display/description boxes relating to facets/filters weren't working or test for mphc search results.
> feat: fixed mphc diplay box css

- test/routes.test.js
Fixed the [hanging test](https://github.com/TheScienceMuseum/collectionsonline/issues/1807) by wrapping it in a try/catch block. It still takes a moment to finish, but does so in a fraction of the time it did before
> test: added try catch for articles test

- lib/helpers/search-results-to-template-data/title-page.js
[Ticket #1356](https://github.com/TheScienceMuseum/collectionsonline/issues/1356)
> Fix search title

- lib/helpers/search-results-to-template-data/title-page.js
- lib/transforms/search-results-to-template-data.js
- templates/pages/person.html
From [this ticket](https://github.com/TheScienceMuseum/collectionsonline/issues/1175) 
There were a few suggestions in the ticket that I couldn't do - i.e text for Documents - archive + makers, as Documents don't have those filters in the filterlist. Also, archives aren't included in the title pages, as this was discussed previously and decided to not include (I assume due to long field names). Similar with dates, we decided not to include in titles.
> Enhance titles 1175

- client/templates.js
- templates/helpers/twoChildRecords.js
- templates/partials/records/record-mph-records.html
Fixed fuzzy images for records with two or less child records, using larger images. Ticket #1864
> feat: fix fuzzy images for 2 or less child records
