TheScienceMuseum/collectionsonline

.travis.yml, package.json, test/example-test.js
Sets up package.json and travis.yml file to run an example test
=> adds initial .travis.yml file #6

package.json, test/example-test.js
Adds semistandard linter and runs it with the tests.
Also fixes the example test file to comply with semistandard rules.
=> adds semistandard linter #4

README.md
To be expanded as project progresses.
=> Add minimal README.md with getting started guide and proposed directory structure

package.json
=> Add pre-commit hook

bin/server.js, package.json, server.js, test/content-negotiation-test.js, test/helpers/test-with-server.js
* Refactors the server to take in config options
* Rewrites server based tests with a helper function that creates a server and calls tape
=> Server refactor

test/content-negotiation-test.js
Adds a test to bring coverage back up
=> adds test for JSON request to search endpoint

README.md
Just a quick update of the README
=> Update directory structure

package.json, templates/layouts/default.html
refs #31
Temporarily adds links to the bower components in the html to get everything working
=> adds bower components to html

README.md
Updated the Readme slightly to include Location as an object type.
=> Added Location (musuem) -> Facility as an object type to Readme

README.md
Clarify Location object as being a museum location / gallery 
(Facility document in Index)
=> Clarify Location object as being a museum location / gallery

src/assets/scss/components/_panel.scss, templates/pages/archive.html, templates/pages/archivedoc.html, templates/pages/object.html, templates/pages/person.html, templates/partials/records/record-related-organisations.html
Added in a new partial and includes for it in the object, people, archive and archive doc templates.
=> Added in an new  partial for related organisations #72

lib/pagination.js, test/pagination.test.js
No minimum on the start index meant negative numbers! Added test and fix.
refs #81
=> Fix negative page numbers

templates/partials/global/search-main.html
gives correct name of icons in tabs on search page
=> fixes missing icons in tabs caused by #84

server.js
=> Allow cross origin requests for API

lib/transforms/json-to-html-data.js, routes/object.js, templates/pages/object.html, templates/partials/records/ondisplay.html, templates/partials/records/record-related-results.html, test/routes.test.js, test/transforms/json-to-html-obj.test.js
Gets some initial attributes for the Object page and renders them
resolves #41
=> Object Page

lib/transforms/json-to-html-data.js, routes/archive.js, templates/pages/archive.html, templates/pages/object.html, templates/partials/records/record-related-documents.html, templates/partials/records/record-related-results.html, test/fixtures/elastic-responses/example-get-response-document.json, test/fixtures/elastic-responses/example-get-response-person.json, test/jsonapi-response-builder-document.test.js, test/jsonapi-response-builder-person.test.js, test/transforms/json-to-html-doc.test.js
Initial rendering of data into document/archive template
resolves #42
=> Initial rendering of document page 

client/lib/search-box.js, client/routes/search.js, client/templates.js, package.json
Apologies I haven't had time to write any tests for this :(
* Adds brfs and loads templates for the client
* Search page requests results from API
* Replaces old results with new ones
refs #48
=> Fetch results AJAX

lib/transforms/json-to-html-data.js, package.json, templates/pages/person.html, templates/partials/records/record-system.html, test/transforms/json-to-html.test.js
=> display the system of a person

client/routes/search.js, client/templates.js, lib/search.js, lib/transforms/search-results-to-jsonapi.js, lib/transforms/search-results-to-template-data.js, routes/search.js, templates/pages/search.html, templates/partials/global/search-main.html, templates/partials/global/search-nav.html, test/helpers/mock-elastic.js, test/search-params.test.js, test/transforms/search-results-to-jsonapi.test.js
see #115 
@nelsonic do you mind to have a look this PR, thanks.
@Danwhy please add your comments too!
=> Add number of result for the categories

lib/jsonapi-response.js, lib/transforms/json-to-html-data.js, templates/partials/records/record-related-people.html, test/client/routes/document.clienttest.js, test/client/routes/object.clienttest.js, test/client/routes/person.clienttest.js, test/fixtures/elastic-responses/example-get-response-document.json, test/fixtures/elastic-responses/example-get-response-object2.json, test/transforms/json-to-html-obj2.test.js
refs #106 and #120 
Gets relevant data for facts/details section of the individual object pages
Facts: 
Details:
=> Visual resource

client/styles/base/_colour.scss, client/templates.js, lib/jsonapi-response.js, lib/transforms/get-values.js, lib/transforms/json-to-html-data.js, lib/transforms/search-results-to-template-data.js, routes/search.js, templates/partials/records/record-related-people.html, templates/partials/records/record-top.html, templates/partials/search/results-grid.html, test/client/routes/document.clienttest.js, test/client/routes/object.clienttest.js, test/client/routes/person.clienttest.js, test/fixtures/elastic-responses/example-get-response-document.json, test/fixtures/elastic-responses/example-get-response-object2.json, test/transforms/json-to-html-obj2.test.js, test/transforms/search-results-to-templates.test.js
Gets and displays the correct data for the search results page.
refs #107 
Person: 
Object:
Archive/Documents:
=> Visual search

lib/jsonapi-response.js
=> fixes bug with objects that have more than one place relationship

client/styles/components/_filter.scss, client/styles/components/_loading.scss, client/styles/components/_search.scss, client/styles/main.scss, templates/partials/search/filters.html
css changes for #68, #60, #113
=> Design updates

client/routes/search.js, client/styles/base/_general.scss, client/templates.js, lib/transforms/json-to-html-data.js, public/hide.js, templates/helpers/getinventorynumber.js, templates/helpers/gettodaysdate.js, templates/partials/records/panel-cite.html, templates/partials/search/results-page.html
=> Visual fixes

package.json
see #179
@Danwhy do you mind to check and merge, thanks!
=> jquery v2.2.4 to work with foundation

lib/query-params/query-params.js, test/query-params.test.js
see #197 and it's also linked to #198 
and the [wiki page doc](https://github.com/TheScienceMuseum/collectionsonline/wiki/Pagination)
=> convert pageNumber and pageSize to number

client/templates.js, lib/query-params/query-params.js, lib/transforms/search-results-to-template-data.js, schemas/search.js, templates/partials/search/results-grid.html, templates/partials/search/results-list.html, templates/partials/search/results-page.html, test/client/filters.clienttest.js, test/client/list-view.clienttest.js
see #214 and the wiki doc on this [page](https://github.com/TheScienceMuseum/collectionsonline/wiki/Grid-View,-List-View-and-No-Result-View)
@nelsonic @Danwhy fancy a small PR to review?
=> display results list view

client/routes/document.js, client/routes/home.js, client/routes/object.js, client/routes/person.js, client/routes/search.js, fixtures/data.js, lib/transforms/json-to-html-data.js, lib/transforms/search-results-to-template-data.js, templates/layouts/default.html, test/client/page-titles.clienttest.js
=> dynamically change the title of the page

templates/partials/search/filters-all.html, templates/partials/search/filters-documents.html, templates/partials/search/filters-objects.html, templates/partials/search/filters-people.html
=> only display non empty facet

templates/layouts/default.html
=> adds twitter card

templates/partials/search/results-list.html
see #233 
@Danwhy do you mind to review and merge, the changes are small.
=> add category date and occupation on the list view

lib/jsonapi-response.js, test/approved-description-obj.test.js, test/fixtures/copy-data.js, test/transforms/json-to-html-obj.test.js
=> grab approved description if defined for object

templates/partials/records/record-related-people.html
=> add icon for related people

client/lib/get-qs.js, client/templates.js, templates/helpers/ifmultiplepages.js, templates/partials/search/results-page.html, test/client/page-number.clienttest.js, test/display-pagination.test.js
=> pagination not displayed on one page result

templates/layouts/default.html
Fixes twitter card title and description #184
=> adds quotes for twitter card

client/lib/get-data.js, routes/plugins/error.js
=> catch ajax 401 error; redirect to login page

client/styles/components/_archive-tree.scss, templates/partials/records/archive-tree-fond.html, templates/partials/records/archive-tree-nest.html
ref #235 
to be merged after #277
=> Archive Block

client/lib/search-listener.js, client/routes/home.js, lib/jsonapi-response.js, lib/search.js, lib/transforms/json-to-html-data.js, schemas/search.js, templates/partials/records/record-top.html, test/filter-links.test.js, test/fixtures/copy-data.js, test/helpers/mock-database.js, test/search-filters.test.js
Adds links from resource pages where filter values are in the details/facts to search page with specific filters applied
=> Filter link

test/fixtures/copy-data.js, test/fixtures/elastic-responses/example-get-response-death.json, test/fixtures/elastic-responses/example-get-response-document.json, test/fixtures/elastic-responses/example-get-response-object.json, test/fixtures/elastic-responses/example-get-response-object2.json, test/fixtures/elastic-responses/example-get-response-organisation.json, test/fixtures/elastic-responses/example-get-response-person.json, test/fixtures/elastic-responses/example-get-response-with-places.json
* Makes the examples human readable
* Makes it easier to see what has changed when the index is updated
=> Format example responses so humans can view them

lib/transforms/json-to-html-data.js
Adds link from resource page to search results with 'object type' filter.
Last facet link from resource page, so closes #150
=> adds link to search object type filter

client/lib/archive-listeners.js, client/lib/get-data.js, client/routes/document.js, client/routes/object.js, client/routes/person.js, client/routes/search.js, client/styles/main.scss, package.json
=> adds error handling for get-data function

.corc.template, package.json, public/sitemap.xml, routes/index.js, routes/sitemap.js, server.js, test/sitemap.test.js
* Proxy `/sitemap.xml` to configured URL `sitemapUrl`
* If no `sitemapUrl` config or `sitemapUrl` is === `baseUrl` then serve local blank `/public/sitemap.xml` file
=> Proxy sitemap

lib/search.js, test/check-purchased.test.js, test/fixtures/copy-data.js, test/helpers/mock-database.js, test/search-documents-filters.test.js, test/search-filters.test.js, test/search-objects-filters.test.js
Explanation of the queries: https://github.com/TheScienceMuseum/collectionsonline/wiki/Search-Query
=> Relevance improvements

templates/pages/person.html
=> fixes alignment of related-people, closes #315

fixtures/attributes.js, lib/jsonapi-response.js, lib/transforms/json-to-html-data.js, test/approved-description-obj.test.js
=> gets correct description for archives, closes #310

lib/transforms/json-to-html-data.js
=> suppresses taxonomy if no value, closes #313

client/routes/home.js, client/templates.js, fixtures/footer-banner.js, fixtures/footer.js, lib/transforms/json-to-html-data.js, lib/transforms/search-results-to-template-data.js, routes/home.js, templates/pages/home.html, templates/partials/global/footer-banner.html, templates/partials/global/global-footer.html
=> build footers from json data

lib/get-archive-and-children.js, templates/partials/records/archive-tree-nest.html
=> fixes showing siblings in archive-browser, closes #312

client/routes/search.js
=> delete unsused clear filter function

templates/layouts/default.html
=> adds google analytics script

lib/transforms/get-values.js, lib/transforms/json-ld.js, lib/transforms/json-to-html-data.js, templates/layouts/default.html, templates/pages/person.html, test/filter-links.test.js
ref #185 
Creates a json object based on keys from [schema.org](https://schema.org/docs/full.html),
then sends that with the rest of the data to be rendered in the head of the page
=> adds JSONLD to HTML 

lib/transforms/get-values.js, lib/transforms/search-results-to-jsonapi.js, test/client/routes/person.clienttest.js
=> Undo Normalisation of Names from AdLib System

lib/facets/aggs-all.js, lib/facets/aggs-objects.js, lib/facets/create-filter-objects.js, lib/search.js, test/fixtures/elastic-responses/example-get-response-death.json, test/fixtures/elastic-responses/example-get-response-document.json, test/fixtures/elastic-responses/example-get-response-object.json, test/fixtures/elastic-responses/example-get-response-object2.json, test/fixtures/elastic-responses/example-get-response-organisation.json, test/fixtures/elastic-responses/example-get-response-person.json, test/fixtures/elastic-responses/example-get-response-with-places.json, test/images.test.js, test/search-accession-numbers.test.js
=> display value of categories in facet

lib/transforms/json-to-html-data.js, lib/transforms/search-results-to-template-data.js, test/client/routes/object.clienttest.js
=> only display name of the category in object page

lib/transforms/get-values.js, lib/transforms/json-to-html-data.js, templates/partials/records/record-details.html, templates/partials/records/record-top.html, test/client/rocket.clienttest.js, test/client/routes/person.clienttest.js, test/routes.test.js
ref #362 #361
Adds links back to the search results page using individual terms rather than concatenated string of occupations/materials/types
=> Serp links

lib/transforms/json-to-html-data.js, templates/partials/records/record-top.html
=> displays only date if no location value for made 

client/styles/base/_helpers.scss, client/styles/components/_control.scss, client/styles/components/_filter.scss, client/styles/components/_record.scss, client/styles/components/_result.scss, client/styles/components/_search.scss
Improves spacing and sizing for small screens, #425 #341
=> Mobile tweaks

templates/pages/person.html
=> suppresses cite block if no description for person 

client/styles/components/_search.scss, lib/transforms/search-results-to-template-data.js, templates/partials/global/search-nav.html, test/client/tabs.clienttest.js
n.b. to reviewer, that js works, but if there is a nicer way to do it, let me know!
=> Disabled tab 430

client/routes/search.js, client/templates.js, public/hide.js, templates/helpers/displayFilters.js, templates/partials/search/results-page.html, test/client/no-results.clienttest.js
=> No results view

lib/transforms/get-values.js, test/fixtures/elastic-responses/example-get-response-object3.json, test/transforms/json-to-html-obj3.test.js
=> displays makers that are not linked

client/lib/get-qs.js, lib/facets/aggs-objects.js, lib/facets/create-filter-objects.js, lib/facets/create-objects-facets.js, lib/query-params/query-params-objects.js, lib/transforms/json-to-html-data.js, schemas/filter.js, templates/partials/search/filters-objects.html, test/search-objects-filters.test.js
ref #401 
Adds materials to the aggregation/filter queries. 
Uses an array for the query parameters, so we can now select multiple materials if the object has more than one
=> adds filters for materials #401

client/styles/components/_record.scss, client/templates.js, lib/transforms/json-to-html-data.js, templates/helpers/taxonomy.js, templates/partials/records/panel-taxonomy.html, templates/partials/records/record-details.html, test/client/routes/object.clienttest.js, test/routes.test.js
=> adds taxonomy to details block

client/lib/download-image.js, client/lib/osd-listener.js, lib/facets/aggs-all.js, lib/facets/create-filters.js, lib/transforms/get-values.js, lib/transforms/json-to-html-data.js, test/filter-links.test.js
ref #419, #448
Link was incorrect for filtering by place.
Also changes the search field from 'name.value' to 'summary_title', as all items with a name have a summary value, but some items only have a summary value, with no name. This ensures we are displaying all the possible filters (ref #449)
=> Place link

lib/transforms/search-results-to-jsonapi.js, test/client/images.clienttest.js, test/search-documents-filters.test.js
=> displays document images on result page

lib/transforms/json-to-html-data.js
=> displays correct value for 'part of archive'

lib/transforms/get-values.js, test/client/images.clienttest.js, test/fixtures/elastic-responses/example-get-response-death.json, test/fixtures/elastic-responses/example-get-response-document.json, test/fixtures/elastic-responses/example-get-response-object.json, test/fixtures/elastic-responses/example-get-response-object2.json, test/fixtures/elastic-responses/example-get-response-organisation.json, test/fixtures/elastic-responses/example-get-response-person.json, test/fixtures/elastic-responses/example-get-response-with-places.json, test/images.test.js
see #488
On this PR:
- change the function which normalise the name of a person by adding trim() to delete all useless white spaces
- get the value of the occupation of a person by selecting the first element of the array
- comment some tests for the images as some items in the index don't have the multimedia property anymore.
@Danwhy do you mind to have a look at this PR. It's possible that the coverage is going down but it will  be back when the multimedia properties will be restored, thanks
=> update test and functions to match new index props

client/lib/filter-results.js, client/lib/loading-bar.js, client/lib/search-listener.js, client/routes/search.js
ref #68
Adds relevant class to searchbar during loading of data
=> adds loading bar animation

lib/transforms/get-values.js, test/helpers/aggregations-all.json, test/routes.test.js
=> suppresses unknown makers 

lib/jsonapi-response.js, lib/transforms/get-values.js, test/client/routes/person.clienttest.js, test/transforms/json-to-html-org.test.js
=> display all occupation in person page

client/styles/components/_awesomplete.scss, client/styles/components/_home.scss, client/styles/components/_search.scss, templates/pages/home.html
After showing and discussing with @jamieu
=> fixes Safari display bug and normalises margins

fixtures/404.js
=> change ids on 404

client/routes/document.js, client/routes/object.js, client/routes/person.js, client/routes/search.js, schemas/search.js
=> fixes json appearing on use of back button 

lib/jsonapi-response.js, package.json, routes/api.js, routes/index.js, templates/partials/records/panel-cite.html, test/error.test.js, test/routes.test.js
ref #240.
Adds link to the cite box that displays the json response from the api
=> adds link to display json api response 

client/lib/split-commas.js, lib/facets/create-facets.js
=> delete old occupation values from facet

lib/transforms/json-to-html-data.js, test/client/routes/document.clienttest.js
=> adds correct copyright value to details block

lib/transforms/search-results-to-template-data.js
=> clears sticky filter when gallery is selected

client/lib/hide-keyboard.js, client/routes/document.js, client/routes/object.js, client/routes/person.js, client/routes/search.js
=> stops keyboard always showing on ios safari 

client/lib/update-active-states-facets.js, test/client/disactive-facet.clienttest.js
=> update facets status to disactive

templates/partials/search/filters-objects.html
=> add logic to ondisplay facet on object

fixtures/footer-banner.js, templates/partials/global/global-footer.html
=> add links to footer-banner

client/main.js, client/routes/museums.js
=> redirect short url to the long one

templates/pages/person.html, templates/partials/records/record-system.html
=> hide system on person page

templates/partials/global/searchbox.html
=> add museum and archive pillbox name

templates/partials/records/record-top.html
=> display "in" if date and place are defined

client/templates.js, lib/transforms/json-to-html-data.js, templates/helpers/comma.js, templates/helpers/isequal.js, templates/partials/records/record-details.html, templates/partials/records/record-top.html, test/filter-links.test.js, test/routes.test.js
=> displays all places made if more than one

templates/layouts/default.html
ref #509
Need to remember to add images once they're back in the index -  #570
=> adds opengraph meta tags 

client/templates.js, lib/get-similar-objects.js, lib/jsonapi-response.js, lib/transforms/json-to-html-data.js, routes/object.js, server.js, templates/helpers/comma.js, templates/helpers/formatrelated.js, templates/helpers/isequal.js, templates/helpers/normalise.js, templates/partials/records/record-details.html, templates/partials/records/record-related-objects.html, templates/partials/records/record-top.html, test/error.test.js, test/filter-links.test.js, test/routes.test.js
ref #271 
Gets objects on display in the same museum or in the same category and displays them in the related objects section.
=> Similar objects

routes/index.js, routes/robot.js, test/routes.test.js
see #493
This PR will require a sitemapUrl property to be added to your .corc config file.
```"sitemapUrl": "http:url_of_the_sitemap"
=> add /robot.txt endpoint

client/lib/hide-keyboard.js, client/lib/polyfills.js, client/main.js, package.json
=> adds polyfills for ie11 support

.travis.yml
Updated travis.yml to add an branch:release provider
=> Add provider for deploying changes to the release branch to production

lib/transforms/get-values.js, templates/partials/records/ondisplay.html, test/fixtures/elastic-responses/example-get-response-death.json, test/fixtures/elastic-responses/example-get-response-document.json, test/fixtures/elastic-responses/example-get-response-object.json, test/fixtures/elastic-responses/example-get-response-object2.json, test/fixtures/elastic-responses/example-get-response-organisation.json, test/fixtures/elastic-responses/example-get-response-person.json, test/fixtures/elastic-responses/example-get-response-with-places.json, test/helpers/aggregations-all.json
link back to the search page
see #581 
to be merged after #591
=> On display link

client/lib/display-filters.js, client/lib/get-data.js, client/routes/search.js
see #586
Check if dom elements exist before manipulating them.
=> check existing dom elts on no result page

client/lib/search-box.js
see #608
At the moment for each search triggered with the "enter" key an unused autocomplete request is also trigger. This PR check the code of the key before executing the autocomplete.
=> do not trigger autocomplete on Enter key

lib/transforms/json-to-html-data.js, templates/layouts/default.html, test/autocomplete.test.js, test/client/routes/person.clienttest.js
=> adds images to twitter/opengraph cards

templates/pages/person.html, test/autocomplete.test.js, test/client/routes/person.clienttest.js
as per #611 (removed, as it can't be commented out because it's a handlebar partial)
=> Remove cite block from people pages

lib/autocomplete.js, lib/search-weights.js, lib/search.js, test/autocomplete.test.js, test/client/routes/person.clienttest.js
Adds the relevance weightings to the autocomplete search
ref #604
=> Autocomplete relevance

lib/autocomplete.js, lib/get-related-items.js, lib/search-weights.js, lib/search.js, lib/sort-related-items.js, templates/partials/records/record-related-objects.html, test/autocomplete.test.js, test/client/routes/person.clienttest.js
ref #626, #603 
Adds relevance to the related items, so we're getting the best ones, and adds images to the cards if they exist
=> Related thumbnails

lib/facets/aggs-all.js, test/autocomplete.test.js, test/client/routes/person.clienttest.js
=> Unknown makers

templates/partials/global/footer-banner.html
=> add link to the footer logo smg

client/lib/search-listener.js, templates/partials/global/searchbox.html, test/client/sticky-filters.clienttest.js
ref issue #624 
Keeps gallery as sticky filter when a new search is made
=> Sticky gallery

lib/cached-document.js, lib/sort-related-items.js
Gets primary identifier for archive tree, as per #645
=> primary identifier

client/lib/to-json-url.js, client/routes/search.js, test/client/multiple-filters.clienttest.js, test/client/next.clienttest.js
fixes #504 without breaking #601
=> fixes json rendering error

lib/get-similar-objects.js
ref #650, adds the search weights to related objects
=> improves relevance of similar/related objects on object pages

client/lib/carousel.js, client/lib/openseadragon.js, templates/partials/records/carousel.html, templates/partials/records/record-imgpanel__controlbar.html, templates/partials/records/single-image.html
=> suppresses zoom button if no zoom exists

fixtures/data.js, templates/pages/home.html, templates/partials/records/panel-cite.html
Very small text changes to homepage and cite block
=> Small text changes to homepage and cite block

routes/route-helpers/content-type.js
=> makes twitter cards/og data work

routes/robot.js
=> add link to sitemap.xml

templates/partials/search/filters-all.html, templates/partials/search/filters-documents.html, templates/partials/search/filters-objects.html
=> move image filter on top

client/lib/carousel.js, client/lib/download-image.js, lib/transforms/json-to-html-data.js, templates/partials/records/carousel.html, templates/partials/records/record-imgpanel__controlbar.html, templates/partials/records/single-image.html
ref #651 
Uses large image for download, also makes download work for all images on carousel, and single images.
=> Download image

lib/transforms/json-to-html-data.js
ref #661 
If web description contains regular description, regular description is suppressed
=> prevents description duplication

lib/transforms/json-to-html-data.js, test/client/rocket.clienttest.js, test/client/routes/object.clienttest.js
=> replaces accession number with object number

client/routes/object.js, templates/partials/records/record-details.html
=> removes cite block from archive pages 

lib/helpers/json-to-html-data/pretty-status.js, lib/transforms/json-to-html-data.js, test/client/rocket.clienttest.js, test/client/routes/object.clienttest.js
=> prettify status

client/templates.js, templates/helpers/formatnumber.js, templates/partials/global/search-nav.html, templates/partials/search/filters-all.html, templates/partials/search/filters-documents.html, templates/partials/search/filters-objects.html, templates/partials/search/filters-people.html
=> formats large numbers

fixtures/footer-banner.js, fixtures/footer.js, test/helpers/aggregations-all.json
Updated some footer links until copy can be agreed.
=> Commercial links

client/lib/archive-listeners.js, test/client/routes/document.clienttest.js
=> makes archive filter work when linked from archive-browser

lib/transforms/get-values.js
Stops error because of ampersands in gallery names: #690
=> encodes display location value

templates/layouts/default.html
=> reorder Google Tag Manager

client/lib/facets-states.js, templates/partials/search/filters-documents.html
=> replaces organisations filter on document serp with people filter

lib/transforms/search-results-to-template-data.js, test/transforms/search-results-to-templates.test.js
=> do not truncate figCaption

lib/helpers/utils.js, lib/museum-mapping.js, routes/route-helpers/parse-params.js, routes/search.js, schemas/search.js, test/client/end-to-end.clienttest.js, test/client/rest-routes.clienttest.js, test/parse-params.test.js, test/routes.test.js, test/utils.test.js
=> redirects rest-style urls to query string based urls

client/lib/carousel.js, client/styles/base/_general.scss, client/styles/base/_hidden.scss, client/styles/main.scss, templates/partials/records/record-imgpanel__controlbar.html
=> only displays use image links if smg have rights

client/styles/base/_helpers.scss, client/styles/components/_carousel.scss, client/styles/components/_record.scss
Makes wide images look better on mobile (#716) and reduces font size of caption (#657)
=> Mobile images

client/styles/components/_carousel.scss
=> add max height on single image

client/styles/components/_record.scss, package.json
heh, fixed without leaving github website :)
=> crop, don't stretch thumbnail images - fixes #727

templates/partials/records/panel-cite.html
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/734
=> added nofollow attribute to in page / cite block API url link

lib/transforms/search-results-to-template-data.js, test/autocomplete.test.js, test/images.test.js
=> Limit pagination

test/autocomplete.test.js, test/images.test.js
=> update tests for new index and relevance

routes/public.js, templates/partials/global/global-header.html, test/autocomplete.test.js, test/images.test.js
=> Clean public.js

lib/jsonapi-response.js, lib/sort-related-items.js, lib/transforms/search-results-to-jsonapi.js, package.json
=> replace slug by slugg package

lib/transforms/json-to-html-data.js
=> delete title for img on document

lib/search-weights.js
ref #772, #771
Boosts fonds records to the top of search results, and the start of related items on people pages
=> boosts fonds records

lib/transforms/get-values.js, lib/transforms/json-to-html-data.js, test/transforms/json-to-html-doc.test.js
ref #744
Correctly extracts date and extent for archives/fonds facts/details
=> Missing Archive Fields

lib/cached-document.js, test/cache.test.js
ref #732 
If there's no Redis connection, we no longer try to get items from the cache and just find them through search
=> Don't use Redis 

client/lib/search-listener.js, lib/helpers/search-results-to-template-data/pillbox-images.js, lib/query-params/query-params-per-category.js, lib/transforms/create-clear-facet-links.js, lib/transforms/search-results-to-template-data.js, templates/partials/global/searchbox.html, templates/partials/search/filters-all.html, templates/partials/search/filters-documents.html, templates/partials/search/filters-objects.html
=> add images pillbox

lib/transforms/get-values.js, lib/transforms/json-ld.js
ref #791
Takes into account index differences to get full jsonld data for adlib people as well as mimsy
=> JSONLD fix

handlers/object-id.js, lib/transforms/json-to-html-data.js, routes/index.js, routes/object-id.js, test/object-id.test.js
see #757
the endpoint /oid/{idObject} will return the following type of json response:
```
{
found: true,
error: null,
searchError: null, // elasticsearch error
path: '/objects/123-456 // id of the object matching IdObject define in the query
}
```
if the query parameter ```?redirect=true``` the page will automatically redirect to the page define by path
=> initialise new route /oid

lib/helpers/json-to-html-data/format-description.js
=> more up the "more" button

templates/partials/records/record-related-documents.html
=> display thumbnails related docs

client/styles/components/_result.scss
=> stops images being squashed vertically

client/lib/osd-listener.js
=> fixes osd crashing safari bug

handlers/object-id.js, test/object-id.test.js
https://github.com/TheScienceMuseum/collectionsonline/issues/757#issuecomment-283954102
=> Modified OID redirect code to return a slugged URL and a 301 response

lib/search.js
=> limit number of pages search

lib/transforms/json-ld.js
=> Resolve issue with ap records that have a type att. but not a nested value  #837

lib/transforms/get-values.js
Resolves #848 until index / extraction process is updated to deal with BCE and CE dates (see https://github.com/TheScienceMuseum/collectionsonline/issues/849)
=> Partial fix for BCE Birth/Death date issue #848

templates/partials/global/global-header.html
=> Remove beta bar from site header

lib/helpers/querify.js
see  #868
For ajax call with js on the front end the format of the query parameters are in camelCase: page[size] = pageSize
=> allow pagination with js

lib/helpers/jsonapi-response/sort-images.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/872
=> Order images by page position if avaliable

fixtures/404.js, routes/plugins/error.js, server.js
ref #893
Adds in the images for the 404 page, except the 'Lost something useful?' poster, which doesn't currently have an image
=> adds images for 404 page

lib/transforms/search-results-to-jsonapi.js, test/transforms/search-results-to-jsonapi.test.js
See #884
Thanks @danwhy for showing me how to fix this
=> Fix prev pagination link fail with error bug

lib/helpers/paramify.js
ref #880
Encodes question marks so the 'Who am I?' gallery filter now works
=> encodes question marks in params

templates/helpers/repeat.js, test/sort-images.test.js
+ Improve coverage in sort-images
+ Removing unused helper
=> Improve coverage

client/routes/resources.js, client/routes/search.js, lib/transforms/search-results-to-template-data.js, lib/transforms/serp-data-layer.js, templates/helpers/normalise.js, templates/layouts/default.html
ref #852
Adds relevant datalayer variables for search/record pages
=> ga datalayer

lib/helpers/utils.js, test/utils.test.js
ref #882
Keeps "and" lowercase in category filters.
=> does not uppercase "and" in categories

lib/transforms/get-values.js
ref #929
changes includes to indexof for ie11 compatibility
=> Fix IE11 bug

templates/partials/records/record-related-documents.html, templates/partials/records/record-related-objects.html, test/client/related.clienttest.js
ref #917
Uses new style of urls, which fixes the issue of the filters not being applied
=> fixes related objects/documents links

lib/helpers/querify.js
ref #914
Encodes ampersands, so they can be used in search
=> encodes ampersands in search query

client/routes/resources.js, client/routes/search.js, lib/transforms/data-layer.js, lib/transforms/serp-data-layer.js, test/transforms/data-layer.test.js
Adds updated data layer variable names + data layer events
ref #852
=> updates analytics variable names

lib/search-weights.js
=> adds placeholder for analytics based boosting

lib/helpers/search-results-to-template-data/title-page.js, test/client/page-titles.clienttest.js, test/title-serp.test.js
ref #913
Title pages for key searches now show correctly
=> makes search title pages correct

lib/pagination.js, test/pagination.test.js
=> Better prev pagination

client/lib/listeners/carousel.js, package.json
=> Fix rotation issues when displaying image

client/routes/resources.js, client/routes/search.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/731
=> Display a better error msg. when connection dropped

lib/get-first.js, lib/get-primary-value.js, test/get-first.test.js
=> Not showing note field, but showing descriptions instead

lib/autocomplete.js, lib/facets/aggs-all.js, lib/facets/create-facets.js, lib/facets/create-filter-all.js, lib/facets/create-filters.js, package.json, test/autocomplete.test.js, test/check-purchased.test.js, test/facets/create-filter-all.test.js, test/facets/create-filter-object.test.js, test/facets/create-filter-people.test.js, test/images.test.js
ref #870
Changes to the code to make it work with the new ES5 index.
We'll have to wait to merge this until we've got the new index running on the staging site
=> code changes for updating to elasticsearch 5

test/client/related.clienttest.js
Comments out failing test so we can deploy the new index
=> comments test out for deployment

client/routes/resources.js, client/routes/search.js
=> Added linebreak to error msg

client/lib/listeners/get-wiki-data.js, routes/index.js, routes/wiki.js
Removes wikipedia image from production server
=> removes wiki from production

client/lib/listeners/carousel.js
Dont run rest of code if `thumnails[flkty.selectedIndex]` isn't defined
=> IOS safari crashing fix

description-boxes/category.json, description-boxes/gallery.json, description-boxes/museum.json, test/client/images.clienttest.js
Updates the text and links in the description boxes.
=> Update desc box text

description-boxes/gallery.json
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/961
=> Resolve issue with Making modern world dec. box not appearing

lib/facets/create-filters.js, test/client/images.clienttest.js, test/facets/create-filter-all.test.js, test/facets/create-filter-object.test.js, test/facets/create-filter-people.test.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/965
=> Resolved date range issue #965

lib/facets/create-filters.js, routes/articles.js, templates/partials/records/record-related-articles.html, test/client/images.clienttest.js, test/facets/create-filter-all.test.js, test/facets/create-filter-object.test.js, test/facets/create-filter-people.test.js, test/routes.test.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/969 by including MSI Manchester articles as well.
(possibly should refactor to run though an array of museums / url endpoints, but works fine for now)
=> Add msim articles

lib/transforms/json-to-html-data.js
fix issues with missing legal attributes on image records
=> fix missing legal attributes on images causing error

fixtures/footer.js, test/client/filters.clienttest.js
https://github.com/TheScienceMuseum/collectionsonline/issues/984
=> Update footer links

lib/transforms/search-results-to-template-data.js, templates/partials/search/results-grid.html, templates/partials/search/results-list.html
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1000
=> Display artists names, instead of category, on SERP cards

description-boxes/category.json
https://github.com/TheScienceMuseum/collectionsonline/issues/999
=> Add Art descriptions to description boxes

lib/transforms/data-layer.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1012
=> Adds displayLocation to GA data layer

client/templates.js, lib/transforms/json-to-html-data.js, templates/helpers/ifsmgorccrights.js, templates/partials/records/record-imgpanel__controlbar.html, test/client/back.clienttest.js, test/client/filters-date.clienttest.js, test/client/multiple-filters.clienttest.js, test/client/next.clienttest.js, test/client/routes/document.clienttest.js, test/routes.test.js
Fixes display of unknown copyright holder and image dropdown for non SMG CC images
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1017
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1016
=> Fixes display of unknown copyright holder and image dropdown 

templates/helpers/ifsmgorccrights.js, test/client/sticky-filters.clienttest.js
Fixes issue where code was checking for `rights.cc` when `rights` didn't exist.
=> fix error with cc licence parsing

lib/transforms/json-to-html-data.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1034
=> Refactor datalayer

lib/transforms/get-values.js, lib/transforms/json-to-html-data.js
#960 - Galleries/categories have correct urls (lowercase, dash separated)
#1038 - Materials urls have correct urls
=> changes links from object pages to correct format

package.json, test/client/back.clienttest.js, test/client/filters-date.clienttest.js, test/client/multiple-filters.clienttest.js, test/client/next.clienttest.js, test/client/sticky-filters.clienttest.js
=> upgrades nightwatch and uncomments nightwatch tests

client/lib/openseadragon.js
=> stops singleImage dataset osd error

client/lib/listeners/search-listener.js, description-boxes/category.json, description-boxes/gallery.json, fixtures/key-categories.js, routes/search.js, test/client/categories.clienttest.js, test/routes.test.js
ref #1004
A search for a key category will now redirect you to the sticky filter serp page for that category, includes synonyms.
=> redirects category queries to category filters

lib/transforms/json-to-html-data.js
=> suppresses image title if it matches description

lib/transforms/json-ld.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1005
=> add new types to JSON-LD

templates/helpers/get-primary-value.js, test/templates/get-primary-vaue.test.js
=> adds get primary value helper

description-boxes/category.json, fixtures/key-categories.js
Adds new terms to redirect to category pages
=> adds additional search terms that redirect to category pages

routes/articles.js
Retrieves articles on main Science Museum site and adds them to sidebar
=> Pull in related articls on main Science Museum site

client/styles/components/_panel.scss, templates/partials/records/record-related-documents-primary.html
Fixes https://github.com/TheScienceMuseum/collectionsonline/issues/1061
=> add doc icon to related archive docs

fixtures/key-categories.js, lib/jsonapi-response.js, lib/transforms/json-to-html-data.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1062
=> add thumbnails and text back to related docs on people and org. pages

routes/search.js, test/routes.test.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1071
=> allow _ga tracking params

package.json, templates/partials/search/filters-all.html
resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1078
=> change place to place of oriign in facets

client/styles/components/_home.scss, fixtures/data.js, templates/pages/home.html
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1079
=> add hyperlinks to filtered  searches within homepage text

client/styles/base/_general.scss
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1076
=> add hairline hover state to musuem links on mobile viewport

schemas/search.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1087
=> remove low page limit from API queries

schemas/search.js
=> remove low page limit from API queries - now 300 pages

test/client/back.clienttest.js
https://github.com/TheScienceMuseum/collectionsonline/issues/1104
=> drop back.clienttest test - to be reinstated

.gitignore, client/routes/search.js, routes/search.js
When a search contains a question starting with "what", we are looking for objects answering the question and redirecting to this object.
The logic needs to be added on the handler and on the client side for it to work with/without javascript on the browser
=> redirect to object when question searched

client/routes/search.js
IE doesn't support startsWith() so switching to a solution using lastIndexOf
=> Fix IE issue with using startsWith

lib/search-weights.js, lib/search.js
https://github.com/TheScienceMuseum/collectionsonline/issues/1124
=> modify search weightings

client/lib/openseadragon.js
- fixed an issue with the second image failing to load as URL didn't have /info.json prefixed
- un-HTML escape cation (may need to revisit and use different JSON friendly encoding)
=> Updates to IIIF

routes/index.js, routes/random.js
Adds route for /random and /slideshow
https://github.com/TheScienceMuseum/collectionsonline/issues/1139
=> Add routes for screensaver and fullscreen random page

package.json
Mainly to fix dependency on old version of loadash
https://github.com/TheScienceMuseum/collectionsonline/issues/1141
=> update ES client to v15.0.0

routes/random.js, routes/screensaver.js
Reverts TheScienceMuseum/collectionsonline#1143
=> Revert "Update screensaver path"

lib/stats.js, routes/index.js, routes/stats.js, test/client/images.clienttest.js
Display counts for various record types
=> Add basic 'stats' route

routes/categories.js, routes/index.js, routes/robot.js, templates/pages/categories.html, test/client/images.clienttest.js
Adds a page that list all categories, mainly for internal / SMG use
https://github.com/TheScienceMuseum/collectionsonline/issues/1187
=> Categories

package.json
Reverts TheScienceMuseum/collectionsonline#1196
=> Revert "Update packages"

lib/transforms/json-ld.js
resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1210
=> Adds types and location to JSON+LD Schema.org markup

lib/helpers/utils.js
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1212
=> Resolves issue with colons in gallery names

lib/search.js, package.json
Resolves 
https://github.com/TheScienceMuseum/collectionsonline/issues/1229
=> Escape ElasticSearch reserved characters

lib/helpers/json-to-html-data/get-description.js
ref: #1241 and https://github.com/TheScienceMuseum/collectionsonline/issues/1241#issuecomment-471987468
Get description from the `description` field instead of the `note` field
=> prioritise description of note

description-boxes/category.json, lib/create-description-box.js, lib/query-params/query-params.js, package.json
ref: https://github.com/TheScienceMuseum/collectionsonline/issues/1008#issuecomment-472481014
Make sure the filter on categories containing dashes work with Elasticsearch
=> Category name with dash

lib/helpers/utils.js, test/parse-params.test.js
ref: https://github.com/TheScienceMuseum/collectionsonline/issues/1080#issuecomment-472961762
=> make sure to allow multiple filters

routes/search.js
=> stops redirecting to category on json calls

client/routes/search.js
ref: #808 
Close filters section on mobile if no filters are selected. On desktop we keep the filters displayed.
=> do not display filters on mobile, #808

lib/sort-related-items.js, routes/person.js, test/related-items.test.js
=> Sends role of person in relation to related objects to front end

routes/index.js, routes/random.js, routes/screensaver.js, test/routes.test.js
=> removes random and screensaver routes

client/lib/loading-bar.js, client/styles/base/_print.scss, client/styles/components/_result.scss
(@jamieu am just fixing this small thing as an exercise while I refresh myself with how this site works!)
=> Various small bug fixes

templates/layouts/default.html
Resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1312
=> Stop ID numbers being seen as tel numbers

templates/partials/records/mediaplayer.html
=> Updates prefix for Sketchfab embeds

.ebextensions/https-redirect-nodejs.config, client/styles/base/_foundation-components.scss
Allow origin domain name though without redirecting to https
=> Modify ebs / nginx proxy settings

package.json
small pkg bump to fix background colour on audio player
=> update the WDS to be compatible with plyr > 3.6

templates/pages/home.html
Updated text from "Explore over 350,000 objects..." to "Explore over 380,000 objects..." :-)
=> Updated number of objects on home 350,000 to 380,000

client/templates.js, description-boxes/collection.json, lib/transforms/json-to-html-data.js, templates/helpers/toggleDetailOpen.js, templates/pages/archive.html, templates/partials/records/record-details.html
=> Updates description box for clockmakers collection and adds Transcripts

test/authentication.test.js, test/client/back.clienttest.js, test/client/filters.clienttest.js, test/client/multiple-filters.clienttest.js, test/client/next.clienttest.js, test/client/related.clienttest.js, test/client/rest-routes.clienttest.js, test/login.test.js, test/search-documents-filters.test.js, test/session-auth.test.js, test/sitemap.test.js, test/static-file.test.js
=> add back broken tests

lib/stats.js, routes/stats.js
https://github.com/TheScienceMuseum/collectionsonline/issues/1516
=> update stats for new layouts

lib/transforms/json-to-html-data.js
Fixes
https://github.com/TheScienceMuseum/collectionsonline/issues/1529
=> remove stray comma

lib/transforms/json-to-html-data.js
parentId can be used as a variable in handlebars
=> Pass parent id child records 1571

client/templates.js, fixtures/attributes.js, lib/facets/aggs-all.js, lib/facets/create-facets.js, lib/facets/create-filters.js, lib/query-params/query-params-objects.js, lib/query-params/query-params-per-category.js, lib/transforms/data-layer.js, lib/transforms/search-results-to-jsonapi.js, lib/transforms/search-results-to-template-data.js, routes/route-helpers/parse-params.js, routes/search.js, schemas/filter.js, templates/helpers/mphShowMore.js, templates/partials/records/record-mph-records.html
Needs to exclude mphc in parse-params to stop co123435 being **C**ap**C**ased to **C**o123435 😱 
https://github.com/TheScienceMuseum/collectionsonline/blob/e80b159ea888eafd1eb9f32ae919ff54d4bfa15e/routes/route-helpers/parse-params.js#L4
for (const cat in categories) {
const exclude = ['has_image', 'object_type', 'material', 'occupation', 'mphc'];
if (cat === 'museum') {
categories[cat] = museumMap.toLong(categories[cat]);
} else if (exclude.indexOf(cat) === -1) {
categories[cat] = utils.uppercaseFirstChar(categories[cat]);
}
}
=> Mph more link filters 1543

lib/helpers/jsonapi-response/sort-images.js, lib/jsonapi-response.js, lib/transforms/json-to-html-data.js, test/sort-images.test.js
**Resolves**
https://github.com/TheScienceMuseum/collectionsonline/issues/1548
https://github.com/TheScienceMuseum/collectionsonline/issues/1597
=> Fix media fields

lib/transforms/get-values.js
resolves https://github.com/TheScienceMuseum/collectionsonline/issues/1545
=> fix makers

templates/pages/about.html
Update the collectionenquiries email address
=> update scmobjectenquiries email

lib/create-description-box.js, templates/partials/global/searchbox.html, templates/partials/search/filters-all.html, templates/partials/search/filters-objects.html
Resolves...
https://github.com/TheScienceMuseum/collectionsonline/issues/1644
https://github.com/TheScienceMuseum/collectionsonline/issues/1645
=> fix coleltion filter being wronglyy displayed

lib/jsonapi-response.js, lib/transforms/json-to-html-data.js
fixes broken name/type link on SPH parts
=> fixes broken name/type link on SPH parts-a

lib/facets/create-filters.js
Fix Worshipable Watchmakers, was not matching on lowercase value in index (so was falling for of the **of**)
=> fix Watchmakers named collection

lib/jsonapi-response.js, lib/transforms/json-to-html-data.js
I have supressed the nested children from MPH records, and tested thoroughly. It would be good to keep testing just to make sure the logic stands up, as I seem to have relatively little test data. Would be good to look at new records to test also
=> feat: supressed nested children from mph records

fixtures/attributes.js, fixtures/galleries.json, lib/facets/aggs-all.js, lib/helpers/jsonapi-response/sort-images.js, test/sort-images.test.js
- updates image sort to use `upload_date` instead of `modification_date`
- update new facility model to **not** publish a `location` element
- adds new `ondisplay` element (for both old and new faculty models)
=> Updates image sort field and changes to on display fields

client/styles/components/_home.scss, client/styles/components/_nav.scss, client/styles/components/_record.scss, templates/pages/home.html
Still a few things to refine in a later commit
=> fix: first pass fixing broken css

lib/helpers/search-results-to-template-data/title-page.js, test/title-serp.test.js
Needs further expanding to integrate search queries into dynamic pages, as there's some complexity there.
=> feat: fixed & expanded dynamic title pages

lib/transforms/json-to-html-data.js
https://github.com/TheScienceMuseum/collectionsonline/issues/1743
=> feat: filtered out parent group id cards where should not appear

client/styles/components/_audio.scss, client/styles/main.scss, lib/transforms/json-to-html-data.js, templates/partials/records/audioplayer.html
Fixed - and added a long comment to close the [ticket](https://github.com/TheScienceMuseum/collectionsonline/issues/1726) and help if needed for reference in future
=> feat: fixed and expanded on audio player component

lib/create-description-box.js, test/create-description-box.test.js
[Issue 1707](https://github.com/TheScienceMuseum/collectionsonline/issues/1707) - Defensive checks and tests added to make the mphc search more robust
=> Invalid uid error mphc 1707

templates/layouts/default.html
[Issue 1744](https://github.com/TheScienceMuseum/collectionsonline/issues/1744) - fixes broken fallback image. Still need to fix dynamic images not showing
=> feat: added absolute path to fallback image

lib/facets/aggs-all.js
=> fix mismatched filter counts

lib/jsonapi-response.js, templates/partials/records/record-sph-item.html
remove log.this from record-sph-item.html which was causing extraneous error logging to console
=> remove log.this from record-sph-item.html

client/styles/components/_panel.scss, test/routes.test.js
Removed console log from wikidata test and also added space between related people and role for [this ticket](https://github.com/TheScienceMuseum/collectionsonline/issues/1799)
=> feat: added space after related people & removed log from wikidata test

client/styles/components/_barcode.scss, client/styles/main.scss, routes/barcode.js, templates/pages/barcode.html
[Ticket 1827](https://github.com/TheScienceMuseum/collectionsonline/issues/1827)
=> Barcode app 1827

routes/barcode.js, templates/layouts/basic.html, templates/layouts/default.html, templates/pages/barcode.html
Adds <title> tag to barcode page and switched to /basic.html handlebars layout template for barcode app
=> Barcode page title

client/lib/listeners/get-wiki-data.js, client/styles/components/_panel.scss, fixtures/wikibasePropertiesConfig.js, lib/wikidataQueries.js, routes/wiki.js, templates/partials/records/wiki-info.html
1st stage improvements for final [Wikidata integration](https://github.com/TheScienceMuseum/collectionsonline/issues/1595) improvments.
Next pass will include:
- Adding link to viaf id 
- Grouping VIAF/OXFNB and putting at bottom of list 
- Parameter to list items
=> Wikidata q codes 1595

lib/jsonapi-response.js, test/routes.test.js
for this [ticket](https://github.com/TheScienceMuseum/collectionsonline/issues/1845)
=> Sph nesting 1845

client/lib/listeners/init-components.js, client/lib/listeners/skipLink.js, client/styles/base/_print.scss, client/styles/components/_scroll-btn.scss, client/styles/components/_skip-link.scss, client/styles/main.scss, templates/pages/404.html, templates/pages/about.html, templates/pages/archive.html, templates/pages/group.html, templates/pages/home.html, templates/pages/object.html, templates/pages/person.html, templates/partials/global/global-header.html, templates/partials/search/results-page.html
[Skip link ticket](https://github.com/TheScienceMuseum/collectionsonline/issues/1309)
=> Add skip link 1309

routes/barcode.js, templates/pages/barcode.html
This fixes the chrome error on the barcode app
=> feat: changed videoConstraints to fix chrome error

client/styles/components/_logo-panel.scss, templates/partials/global/logo-panel.html
=> feat: back to top btn

templates/pages/about.html, templates/pages/archive.html, templates/pages/explore.html, templates/pages/group.html, templates/pages/home.html, templates/pages/person.html, templates/partials/global/global-header.html, templates/partials/global/searchbox.html, templates/partials/global/smg-map.html, templates/partials/records/archive-tree-browser.html, templates/partials/records/mediaplayer.html, templates/partials/records/wiki-info.html
Post-review, a few further fixes
=> Further A11Y amends

lib/jsonapi-response.js, lib/search-weights.js, lib/transforms/json-to-html-data.js, routes/neverbeenseen.js
Fixes issue with broken group pages
ie. 
https://collection.sciencemuseumgroup.org.uk/objects/co9028715/butter-knife-with-purple-parkesine-handle-steel-blades
=> resolves issue with broken group records

lib/search-weights.js, routes/neverbeenseen.js
- reinstates GA ranking
- reinstates /neverbeenseen
=> reinstate GA ranking and neverbeenseen

description-boxes/gallery.json
fix syntax in gallery description file
=> add new galleries
